apiVersion: v1
kind: Pod
metadata:
  name: command-demo2
  labels:
    purpose: demonstrate-command
spec:
  containers:
    - name: command-demo-container2
      image: debian
      env:
        - name: MESSAGE
          value: "hello world"
      command: ["/bin/echo"]
      args: ["$(MESSAGE)"]
#      command: [ "/bin/sh" ]
#      args: ["-c", "while true; do echo hello; sleep 10;done"]
  restartPolicy: OnFailure
