apiVersion: v1
kind: Pod
metadata:
  name: my-web
  labels:
    env: prod
    app: main
    tier: frontend
    owner: Dill
spec:
  containers:
    - name: container-java
      image: dilitand/java:latest
      ports:
        - containerPort: 80