apiVersion: v1
kind: Pod
metadata:
  name: my-web2
  labels:
    env: prod
    app: main
    tier: frontend
    owner: Dill
spec:
  containers:
    - name: container-java
      image: dilitand/java:latest
      ports:
        - containerPort: 8890
    - name: container-api
      image: tomcat:8.5.38
      ports:
        - containerPort: 8080